export type PageExtra = {
  kicker: string;
  referenceTitle: string;
  referenceNote: string;
  summary: string;
  facts: { label: string; value: string; note: string }[];
  checks: string[];
  links: { href: string; label: string; text: string }[];
};

export const pageExtras: Record<string, PageExtra> = {
  '린M충전': { kicker:'CHARGE GUIDE', referenceTitle:'린M 다이아 충전 상품', referenceNote:'충전 수량과 원화 가격은 게임 업데이트에 따라 달라질 수 있습니다.', summary:'린M 충전 상품은 60~6480 다이아의 여러 원화 결제 구간으로 구성되어 있어 필요한 수량과 가격을 비교해 선택할 수 있습니다.', facts:[{label:'60 다이아',value:'1,500원',note:'첫 충전 혜택 표시'},{label:'680 다이아',value:'15,000원',note:'충전 상품 구간'},{label:'3,280 다이아',value:'75,000원',note:'충전 상품 구간'},{label:'6,480 다이아',value:'149,000원',note:'표시된 상위 구간'}], checks:['다이아·귀속 다이아 등 재화를 구분합니다.','첫 충전 혜택이 현재 계정에 적용되는지 확인합니다.','결제 직전 수량과 원화 금액을 다시 확인합니다.'], links:[{href:'/린M가격',label:'린M 다이아 가격표',text:'수량별 충전 금액 전체 비교'},{href:'/린M다이아',label:'린M 다이아 사용처',text:'일반·귀속 다이아 차이와 사용처'},{href:'/린M충전방법',label:'린M 충전방법',text:'게임 내 충전 순서와 결제 전 확인'}] },
  '린M다이아': { kicker:'DIAMOND TYPES', referenceTitle:'일반 다이아와 귀속 다이아', referenceNote:'상점 메뉴에 따라 사용하는 재화와 상품 구성이 달라질 수 있습니다.', summary:'린M에서는 일반 다이아, 귀속 다이아, 미네랄, 포인트처럼 용도가 다른 재화를 구분해 사용하는 것이 중요합니다.', facts:[{label:'일반 다이아',value:'충전 가능',note:'상점 재료·특수상품 등에 사용'},{label:'귀속 다이아',value:'별도 상점',note:'전용 상품 확인'},{label:'미네랄',value:'교환 재화',note:'강화석·돌파석 등'},{label:'포인트',value:'포인트 상점',note:'일부 상자·아이템 구매'}], checks:['상품 옆 재화 아이콘을 확인합니다.','레벨 해금 조건을 확인합니다.','일일·주간·월간 구매 제한을 함께 봅니다.'], links:[{href:'/린M아이템',label:'린M 상점 아이템',text:'재료·마법석·특수 아이템 살펴보기'},{href:'/린M가격',label:'린M 가격표',text:'다이아 충전 금액과 재화별 가격 비교'},{href:'/린M가이드',label:'린M 초보 가이드',text:'재화·상점·구매 제한 기본 안내'}] },
  '린M아이템': { kicker:'STORE ITEMS', referenceTitle:'린M 상점 아이템 종류', referenceNote:'상품별 해금 조건과 사용 재화는 구매 화면에서 함께 확인하세요.', summary:'린M 상점에는 재료·특수 아이템·잡화·마법석 등 다양한 상품이 있으며 상품마다 해금 조건과 구매 제한이 다를 수 있습니다.', facts:[{label:'신기석',value:'재료 아이템',note:'해금 조건 확인'},{label:'성석 가루',value:'재료 아이템',note:'사용 재화 확인'},{label:'탈것 영혼',value:'성장 재료',note:'상점별 조건 확인'},{label:'마법석',value:'여러 종류',note:'레벨 조건 확인'}], checks:['현재 캐릭터 레벨로 해금됐는지 확인합니다.','같은 이름의 아이템이 다른 상점에도 있는지 확인합니다.','구매 제한이 있는지 확인합니다.'], links:[{href:'/린M패키지',label:'린M 패키지 구성',text:'상자형 상품과 구매 제한 살펴보기'},{href:'/린M다이아',label:'린M 다이아 사용처',text:'아이템 구매에 쓰이는 재화 구분'},{href:'/린M가격',label:'린M 상점 가격',text:'충전 금액과 상점 가격 구조 비교'}] },
  '린M패키지': { kicker:'LIMITED GOODS', referenceTitle:'린M 패키지와 상자형 상품', referenceNote:'상품별 일일·주간 구매 제한과 레벨 조건을 함께 살펴보세요.', summary:'서프라이즈 상자, 마법석 상자, 미네랄 주머니 등 상자형 상품은 구성과 구매 제한을 함께 비교하는 것이 좋습니다.', facts:[{label:'미네랄 주머니',value:'500→400',note:'20% 표시·일일 제한'},{label:'마법석 상자',value:'상자형 상품',note:'레벨 조건 확인'},{label:'주간 제한',value:'상품별 상이',note:'남은 횟수 확인'},{label:'일일 제한',value:'상품별 상이',note:'남은 횟수 확인'}], checks:['상자 사용 시 획득 내용을 확인합니다.','일일·주간 구매 가능 횟수를 확인합니다.','레벨 해금 조건을 확인합니다.'], links:[{href:'/린M할인',label:'린M 한정 할인',text:'패키지·상품별 할인 조건 살펴보기'},{href:'/린M아이템',label:'린M 아이템 정보',text:'상점 상품과 재료 종류 확인'},{href:'/린M가격',label:'린M 가격표',text:'다이아 충전 금액과 상점 가격 비교'}] },
  '린M가격': { kicker:'PRICE TABLE', referenceTitle:'린M 다이아 가격표', referenceNote:'충전 금액과 게임 내 상점 가격은 업데이트에 따라 변경될 수 있습니다.', summary:'린M 가격 페이지에서는 다이아 원화 충전 금액과 일반·귀속 다이아·미네랄·포인트 상점의 가격 구조를 구분해 비교합니다.', facts:[{label:'300 다이아',value:'7,500원',note:'충전 구간'},{label:'980 다이아',value:'22,000원',note:'충전 구간'},{label:'1,980 다이아',value:'45,000원',note:'충전 구간'},{label:'6,480 다이아',value:'149,000원',note:'충전 구간'}], checks:['원화 가격과 게임 내 재화 가격을 혼동하지 않습니다.','할인 전·후 가격이 따로 표시되는지 확인합니다.','업데이트 후 가격 변경 여부를 확인합니다.'], links:[{href:'/린M충전',label:'린M 충전 상품',text:'다이아 충전 구성과 첫 충전 혜택'},{href:'/린M할인',label:'린M 할인 상품',text:'한정 할인과 할인 전후 가격 확인'},{href:'/린M다이아',label:'린M 다이아 사용처',text:'일반·귀속 다이아 차이 확인'}] },
  '린M충전방법': { kicker:'IN-GAME FLOW', referenceTitle:'린M 충전방법 순서', referenceNote:'상점의 충전 메뉴에서 수량과 가격, 계정별 혜택을 차례로 확인하세요.', summary:'린M 충전방법은 상점 진입 → 충전 메뉴 선택 → 다이아 수량·가격 확인 → 결제 전 혜택 확인 순으로 살펴보면 이해하기 쉽습니다.', facts:[{label:'STEP 01',value:'상점 진입',note:'메뉴 확인'},{label:'STEP 02',value:'충전 선택',note:'다이아 상점과 구분'},{label:'STEP 03',value:'수량 선택',note:'여러 충전 구간 비교'},{label:'STEP 04',value:'최종 확인',note:'가격·혜택·계정 상태'}], checks:['첫 충전 혜택이 남아 있는지 확인합니다.','외부 프로모션과 게임 내 가격을 구분합니다.','점검 중에는 결제가 불가능할 수 있습니다.'], links:[{href:'/린M충전',label:'린M 충전 상품 확인',text:'다이아 수량별 충전 구성 보기'},{href:'/린M가격',label:'린M 다이아 가격표',text:'수량별 원화 충전 금액 비교'},{href:'/린M업데이트',label:'린M 업데이트·점검',text:'점검 일정과 결제 제한 확인'}] },
  '린M할인': { kicker:'DISCOUNT GUIDE', referenceTitle:'린M 한정 할인과 프로모션', referenceNote:'게임 내 할인과 기간형 외부 프로모션은 적용 조건이 서로 다릅니다.', summary:'린M 할인은 상품별 할인율과 구매 제한을 확인하고, 기간형 프로모션은 시작일·종료일과 대상 조건을 따로 살펴보는 것이 중요합니다.', facts:[{label:'미네랄 주머니',value:'20% 할인',note:'500→400 표시'},{label:'탈것 영혼',value:'20% 할인',note:'30→24 표시'},{label:'기간형 행사',value:'종료 여부 확인',note:'행사 날짜 확인'},{label:'구매 제한',value:'상품별 상이',note:'일일·주간 조건'}], checks:['종료된 프로모션을 현재 할인으로 보지 않습니다.','대상 회원·결제수단·기간을 확인합니다.','게임 내 구매 제한을 함께 확인합니다.'], links:[{href:'/린M이벤트',label:'린M 이벤트 기간',text:'공식 이벤트와 프로모션 종료 여부 확인'},{href:'/린M가격',label:'린M 기본 가격표',text:'할인 전 충전·상점 가격과 비교'},{href:'/린M충전',label:'린M 충전 상품',text:'다이아 충전 구성과 혜택 확인'}] },
  '린M자주묻는질문': { kicker:'LINM FAQ', referenceTitle:'린M 자주 묻는 질문', referenceNote:'다이아·충전·상점·할인과 관련해 자주 찾는 내용을 주제별로 안내합니다.', summary:'린M FAQ에서는 재화 종류, 레벨 해금, 구매 제한, 첫 충전 혜택과 점검 중 결제 제한 등 자주 궁금한 내용을 빠르게 찾을 수 있습니다.', facts:[{label:'게임',value:'린M: 잊혀진 유산',note:'게임 식별'},{label:'재화',value:'여러 종류',note:'다이아·귀속 다이아·미네랄·포인트'},{label:'해금',value:'레벨 조건 존재',note:'상품별 상이'},{label:'점검',value:'결제 제한 가능',note:'점검 일정 확인'}], checks:['상품명과 재화 종류를 확인합니다.','현재 레벨과 구매 가능 횟수를 확인합니다.','이벤트·점검은 날짜와 상태를 확인합니다.'], links:[{href:'/린M가이드',label:'린M 초보 가이드',text:'재화와 상점 구조부터 살펴보기'},{href:'/린M업데이트',label:'린M 업데이트·점검',text:'점검 일정과 변경사항 확인'},{href:'/린M가격',label:'린M 다이아 가격표',text:'수량별 충전 금액 비교'}] },
  '린M가이드': { kicker:'BEGINNER GUIDE', referenceTitle:'린M 초보 상점 가이드', referenceNote:'재화·해금 레벨·구매 제한을 구분하면 상점 구조를 이해하기 쉽습니다.', summary:'린M을 처음 시작했다면 일반 다이아, 귀속 다이아, 미네랄, 포인트를 구분하고 상품별 해금 조건과 구매 제한을 순서대로 살펴보세요.', facts:[{label:'재화 1',value:'일반 다이아',note:'충전 가능'},{label:'재화 2',value:'귀속 다이아',note:'별도 상점'},{label:'재화 3',value:'미네랄',note:'교환 상품'},{label:'재화 4',value:'포인트',note:'포인트 상점'}], checks:['가격 옆 아이콘으로 재화를 구분합니다.','‘달성 시 해제’ 문구를 확인합니다.','일일·주간·월간 제한을 확인합니다.'], links:[{href:'/린M다이아',label:'린M 다이아 종류·사용처',text:'일반·귀속 다이아 차이 알아보기'},{href:'/린M아이템',label:'린M 상점 아이템',text:'재료·마법석·특수 아이템 확인'},{href:'/린M업데이트',label:'린M 업데이트 정보',text:'점검 일정과 변경사항 살펴보기'}] },
  '린M이벤트': { kicker:'EVENT GUIDE', referenceTitle:'린M 이벤트 기간과 상태', referenceNote:'이벤트는 시작일과 종료일을 기준으로 현재 참여 가능 여부를 구분하세요.', summary:'린M 이벤트 페이지에서는 기간형 공식 이벤트와 프로모션의 일정, 대상, 혜택 조건과 종료 여부를 구분해 안내합니다.', facts:[{label:'프로모션',value:'기간 확인',note:'시작일·종료일'},{label:'참여 대상',value:'행사별 상이',note:'대상 조건 확인'},{label:'혜택',value:'행사별 상이',note:'쿠폰·보상 조건'},{label:'종료 여부',value:'날짜로 구분',note:'현재 참여 가능 여부'}], checks:['시작일과 종료일을 함께 확인합니다.','종료 이벤트는 현재 혜택으로 보지 않습니다.','새 이벤트는 참여 대상과 조건을 확인합니다.'], links:[{href:'/린M할인',label:'린M 할인·프로모션',text:'게임 내 할인과 외부 프로모션 비교'},{href:'/린M업데이트',label:'린M 업데이트·점검',text:'점검 일정과 변경사항 확인'},{href:'/린M가이드',label:'린M 초보 가이드',text:'상점과 재화 기본 구조 살펴보기'}] },
  '린M업데이트': { kicker:'UPDATE GUIDE', referenceTitle:'린M 업데이트와 점검 정보', referenceNote:'점검 일정과 보상, 변경사항은 날짜별로 구분해 확인하세요.', summary:'린M 업데이트 페이지에서는 점검 시간, 보상, 변경사항과 점검 중 이용 제한처럼 업데이트 때 알아둘 내용을 날짜별로 살펴볼 수 있습니다.', facts:[{label:'점검일',value:'2026-08-28',note:'완료된 점검 기록'},{label:'시간',value:'10:00~11:00',note:'점검 시간'},{label:'보상',value:'귀속 다이아 200',note:'공지된 보상'},{label:'변경',value:'일부 표기 오류 수정',note:'공지된 변경사항'}], checks:['점검 중 접속·결제가 제한될 수 있습니다.','보상 지급 상태는 게임 내에서 확인합니다.','점검 시간·내용은 변경될 수 있습니다.'], links:[{href:'/린M이벤트',label:'린M 이벤트 정보',text:'이벤트 기간과 종료 여부 살펴보기'},{href:'/린M충전방법',label:'린M 충전방법',text:'충전 순서와 점검 중 결제 주의'},{href:'/린M가이드',label:'린M 초보 가이드',text:'재화와 상점 이용 기본 확인'}] }
};