export type PageExtra = {
  kicker: string;
  referenceTitle: string;
  referenceNote: string;
  summary: string;
  facts: { label: string; value: string; note: string }[];
  checks: string[];
  links: { href: string; label: string; text: string }[];
};

export const pageExtras: Record<string, PageExtra> = {
  '린M충전': { kicker:'VERIFIED CHARGE', referenceTitle:'실제 충전 화면 기준', referenceNote:'2026-09-02 제공 스크린샷 기준. 계정·업데이트에 따라 변동 가능.', summary:'실제 충전 화면에서 60~6480 다이아의 8개 원화 결제 구간이 확인됩니다.', facts:[{label:'60 다이아',value:'1,500원',note:'첫 충전 혜택 표시'},{label:'680 다이아',value:'15,000원',note:'실제 화면 확인'},{label:'3,280 다이아',value:'75,000원',note:'실제 화면 확인'},{label:'6,480 다이아',value:'149,000원',note:'최대 표시 구간'}], checks:['다이아·귀속 다이아 등 재화를 구분합니다.','첫 충전 혜택이 현재 계정에 적용되는지 확인합니다.','결제 직전 수량과 원화 금액을 다시 확인합니다.'], links:[{href:'/린M가격',label:'린M 가격',text:'전체 충전 가격표 확인'},{href:'/린M다이아',label:'린M 다이아',text:'재화별 차이 확인'},{href:'/린M충전방법',label:'린M 충전방법',text:'게임 내 충전 흐름'}] },
  '린M다이아': { kicker:'DIAMOND TYPES', referenceTitle:'일반 다이아와 귀속 다이아', referenceNote:'실제 상점에서 메뉴와 가격 재화가 별도로 구분됩니다.', summary:'린M 상점은 일반 다이아, 귀속 다이아, 미네랄, 포인트를 서로 다른 재화로 운용합니다.', facts:[{label:'일반 다이아',value:'충전 가능',note:'상점 재료·특수상품 등에 사용'},{label:'귀속 다이아',value:'별도 상점',note:'잡화 등 전용 상품 확인'},{label:'미네랄',value:'교환 재화',note:'강화석·돌파석 등'},{label:'포인트',value:'포인트 상점',note:'일부 상자·아이템 구매'}], checks:['상품 옆 재화 아이콘을 확인합니다.','레벨 해금 조건을 확인합니다.','일일·주간·월간 구매 제한을 함께 봅니다.'], links:[{href:'/린M아이템',label:'린M 아이템',text:'실제 상점 아이템 보기'},{href:'/린M가격',label:'린M 가격',text:'재화별 가격 예시'},{href:'/린M가이드',label:'린M 가이드',text:'재화 구조 초보 안내'}] },
  '린M아이템': { kicker:'STORE ITEMS', referenceTitle:'실제 상점에서 확인된 아이템', referenceNote:'스크린샷에 표시된 상품명과 해금 조건만 반영합니다.', summary:'재료·특수 아이템·잡화·마법석 등 다양한 상점 상품이 확인됩니다.', facts:[{label:'신기석',value:'80 다이아',note:'재료 탭'},{label:'성석 가루',value:'50 다이아',note:'재료 탭'},{label:'탈것 영혼',value:'30 다이아',note:'재료 화면'},{label:'한 송이 장미',value:'100 귀속 다이아',note:'귀속 다이아 잡화'}], checks:['현재 캐릭터 레벨로 해금됐는지 확인합니다.','같은 이름의 아이템이 다른 상점에도 있는지 확인합니다.','구매 제한이 있는지 확인합니다.'], links:[{href:'/린M패키지',label:'린M 패키지',text:'상자형·제한형 상품'},{href:'/린M다이아',label:'린M 다이아',text:'사용 재화 구분'},{href:'/린M가격',label:'린M 가격',text:'실제 가격 예시'}] },
  '린M패키지': { kicker:'LIMITED GOODS', referenceTitle:'상자형 상품과 구매 제한', referenceNote:'일일·주간 구매 제한이 실제 상점에 표시됩니다.', summary:'서프라이즈 상자, 마법석 상자, 미네랄 주머니 등 상자형 상품과 제한 구매 구조가 확인됩니다.', facts:[{label:'미네랄 주머니',value:'500→400',note:'20% 표시·일일 제한'},{label:'마법석 상자',value:'상자형 상품',note:'레벨 조건 확인'},{label:'주간 제한',value:'30/30·100/100',note:'상품별 상이'},{label:'일일 제한',value:'1/1·3/3',note:'상품별 상이'}], checks:['상자 사용 시 획득 내용을 확인합니다.','일일·주간 구매 가능 횟수를 확인합니다.','레벨 해금 조건을 확인합니다.'], links:[{href:'/린M할인',label:'린M 할인',text:'한정 할인 사례'},{href:'/린M아이템',label:'린M 아이템',text:'상점 상품 종류'},{href:'/린M가격',label:'린M 가격',text:'표시 가격 확인'}] },
  '린M가격': { kicker:'PRICE TABLE', referenceTitle:'실제 화면에서 확인한 가격', referenceNote:'2026-09-02 화면 기준 기록이며 이후 변경될 수 있습니다.', summary:'다이아 원화 충전 가격과 다이아·귀속 다이아·미네랄·포인트 상점 가격을 구분해 봅니다.', facts:[{label:'300 다이아',value:'7,500원',note:'충전 화면'},{label:'980 다이아',value:'22,000원',note:'충전 화면'},{label:'1,980 다이아',value:'45,000원',note:'충전 화면'},{label:'6,480 다이아',value:'149,000원',note:'충전 화면'}], checks:['원화 가격과 게임 내 재화 가격을 혼동하지 않습니다.','할인 전·후 가격이 따로 표시되는지 확인합니다.','업데이트 후 가격 변경 여부를 확인합니다.'], links:[{href:'/린M충전',label:'린M 충전',text:'전체 충전 구간'},{href:'/린M할인',label:'린M 할인',text:'할인 전후 가격'},{href:'/린M다이아',label:'린M 다이아',text:'재화별 사용처'}] },
  '린M충전방법': { kicker:'IN-GAME FLOW', referenceTitle:'실제 게임 내 충전 흐름', referenceNote:'우측 상점 메뉴에서 충전 화면으로 진입하는 구조가 확인됩니다.', summary:'상점 → 충전 → 수량·가격 확인 → 계정별 첫 충전 혜택 확인 순으로 보는 것이 안전합니다.', facts:[{label:'STEP 01',value:'상점 진입',note:'우측 메뉴 확인'},{label:'STEP 02',value:'충전 선택',note:'다이아 메뉴와 구분'},{label:'STEP 03',value:'수량 선택',note:'60~6480 구간'},{label:'STEP 04',value:'최종 확인',note:'가격·혜택·계정 상태'}], checks:['첫 충전 혜택이 남아 있는지 확인합니다.','외부 프로모션과 게임 내 가격을 구분합니다.','점검 중에는 결제가 불가능할 수 있습니다.'], links:[{href:'/린M충전',label:'린M 충전',text:'충전 상품 확인'},{href:'/린M가격',label:'린M 가격',text:'원화 가격표'},{href:'/린M업데이트',label:'린M 업데이트',text:'점검 및 결제 제한 확인'}] },
  '린M할인': { kicker:'DISCOUNT FACTS', referenceTitle:'실제 할인 표시와 공식 프로모션', referenceNote:'현재 할인과 과거 종료 프로모션을 구분합니다.', summary:'게임 내 한정 할인은 상품별 할인율·구매 제한이 있고, 원스토어 프로모션은 별도 기간·대상 조건이 있습니다.', facts:[{label:'미네랄 주머니',value:'20% 할인',note:'500→400 다이아'},{label:'탈것 영혼',value:'20% 할인',note:'30→24 다이아'},{label:'겜캉스 피날레',value:'종료',note:'2026-08-21~25'},{label:'ONE pay',value:'과거 20% 포인트백',note:'공지 기록 기준'}], checks:['종료된 프로모션을 현재 할인으로 보지 않습니다.','대상 회원·결제수단·기간을 확인합니다.','게임 내 구매 제한을 함께 확인합니다.'], links:[{href:'/린M이벤트',label:'린M 이벤트',text:'프로모션 종료 여부'},{href:'/린M가격',label:'린M 가격',text:'기본 가격과 비교'},{href:'/린M충전',label:'린M 충전',text:'충전 상품 가격'}] },
  '린M자주묻는질문': { kicker:'FACT FAQ', referenceTitle:'실제 자료에서 확인되는 핵심 질문', referenceNote:'추정 답변 대신 상점 화면과 공식 공지에서 확인되는 범위만 답합니다.', summary:'재화 종류, 레벨 해금, 구매 제한, 첫 충전 혜택, 점검 중 결제 제한을 중심으로 확인합니다.', facts:[{label:'게임',value:'린M: 잊혀진 유산',note:'리니지M과 구분'},{label:'재화',value:'여러 종류',note:'다이아·귀속 다이아·미네랄·포인트'},{label:'해금',value:'레벨 조건 존재',note:'상품별 상이'},{label:'점검',value:'결제 불가 가능',note:'공식 점검 공지 확인'}], checks:['상품명과 재화 종류를 확인합니다.','현재 레벨과 구매 가능 횟수를 확인합니다.','이벤트·점검은 최신 공식 공지를 확인합니다.'], links:[{href:'/린M가이드',label:'린M 가이드',text:'상점 구조 이해'},{href:'/린M업데이트',label:'린M 업데이트',text:'최신 점검 정보'},{href:'/린M가격',label:'린M 가격',text:'실제 가격 확인'}] },
  '린M가이드': { kicker:'BEGINNER FACT GUIDE', referenceTitle:'상점 화면을 읽는 법', referenceNote:'재화·해금 레벨·구매 제한을 먼저 읽으면 상품 구조를 이해하기 쉽습니다.', summary:'린M 상점은 여러 재화와 레벨 조건, 구매 제한이 겹쳐 있으므로 아이콘과 조건을 함께 확인해야 합니다.', facts:[{label:'재화 1',value:'일반 다이아',note:'충전 가능'},{label:'재화 2',value:'귀속 다이아',note:'별도 상점'},{label:'재화 3',value:'미네랄',note:'교환 상품'},{label:'재화 4',value:'포인트',note:'포인트 상점'}], checks:['가격 옆 아이콘으로 재화를 구분합니다.','‘달성 시 해제’ 문구를 확인합니다.','일일·주간·월간 제한을 확인합니다.'], links:[{href:'/린M다이아',label:'린M 다이아',text:'재화 구분'},{href:'/린M아이템',label:'린M 아이템',text:'실제 상품 예시'},{href:'/린M업데이트',label:'린M 업데이트',text:'최신 변경사항'}] },
  '린M이벤트': { kicker:'OFFICIAL EVENT LOG', referenceTitle:'최근 공식 이벤트 상태', referenceNote:'수집일 2026-09-02 기준 종료 여부를 날짜로 판정합니다.', summary:'최근 수집된 공식 자료의 8월 이벤트와 원스토어 프로모션은 종료일을 지난 기록으로 분류합니다.', facts:[{label:'겜캉스 피날레',value:'종료',note:'8/21~8/25'},{label:'대상',value:'본인 인증 원스토어 회원',note:'공식 공지'},{label:'쿠폰',value:'15%·20%·50% 등',note:'과거 이벤트 조건'},{label:'라운지 이벤트',value:'8/31 종료 기록',note:'수집 자료 기준'}], checks:['시작일과 종료일을 함께 확인합니다.','종료 이벤트는 현재 혜택으로 표시하지 않습니다.','새 이벤트는 공식 라운지 확인 후 반영합니다.'], links:[{href:'/린M할인',label:'린M 할인',text:'과거 할인 프로모션'},{href:'/린M업데이트',label:'린M 업데이트',text:'최근 공식 공지'},{href:'/린M가이드',label:'린M 가이드',text:'이벤트 전 기본 구조'}] },
  '린M업데이트': { kicker:'LATEST OFFICIAL UPDATE', referenceTitle:'2026년 8월 28일 최신 점검', referenceNote:'업로드된 공식 라운지 수집 자료에서 가장 최근 확인되는 업데이트 공지.', summary:'8월 28일 10:00~11:00 전체 서버 점검, 귀속 다이아 200 보상, 일부 표기 오류 수정이 확인됩니다.', facts:[{label:'점검일',value:'2026-08-28',note:'점검 완료'},{label:'시간',value:'10:00~11:00',note:'공식 공지'},{label:'보상',value:'귀속 다이아 200',note:'게임 내 우편'},{label:'변경',value:'일부 표기 오류 수정',note:'공지 명시'}], checks:['점검 중 접속·결제가 불가능할 수 있습니다.','보상은 점검 후 게임 내 우편을 확인합니다.','점검 시간·내용은 변경될 수 있습니다.'], links:[{href:'/린M이벤트',label:'린M 이벤트',text:'공식 이벤트 상태'},{href:'/린M충전방법',label:'린M 충전방법',text:'점검 중 결제 주의'},{href:'/린M가이드',label:'린M 가이드',text:'상점 기본 구조'}] }
};
