export type PageExtra = {
  kicker: string;
  referenceTitle: string;
  referenceNote: string;
  summary: string;
  facts: { label: string; value: string; note: string }[];
  checks: string[];
  links: { href: string; label: string; text: string }[];
};

export const pageExtras: Record<string, PageExtra> = {
  '린M다이아': { kicker:'DIAMOND REFERENCE', referenceTitle:'먼저 확인할 다이아 기준 정보', referenceNote:'공식 스토어 기준 정보와 몽땅 다이아 상담 조건은 구분해 확인합니다.', summary:'린M: 잊혀진 유산의 다이아는 수량뿐 아니라 필요한 사용 목적과 패키지 포함 여부를 함께 확인하는 것이 좋습니다.', facts:[{label:'다이아',value:'핵심 재화',note:'수량과 사용 목적 확인'},{label:'단품',value:'수량 기준 비교',note:'필요 수량을 먼저 결정'},{label:'패키지',value:'구성 기준 비교',note:'단품과 별도로 판단'}], checks:['구매하려는 수량과 사용 목적을 먼저 확인합니다.','다이아 단품과 패키지는 분리해 비교합니다.','최종 상담 조건은 신청 전에 다시 확인합니다.'], links:[{href:'/린M가격',label:'린M 가격',text:'상품별 가격 비교 기준 확인'},{href:'/린M충전',label:'린M 충전',text:'충전 상품과 이용 전 확인사항'},{href:'/린M패키지',label:'린M 패키지',text:'패키지 구성과 선택 기준'}] },
  '린M충전': { kicker:'CHARGE GUIDE', referenceTitle:'충전 전에 상품 유형부터 확인하세요', referenceNote:'정확한 게임명과 상품명, 수량을 먼저 확인하면 상담 과정에서 혼선을 줄일 수 있습니다.', summary:'린M 충전 페이지는 무엇을 충전할 수 있고 무엇을 확인해야 하는지에 집중합니다.', facts:[{label:'다이아',value:'수량형 상품',note:'필요 수량 확인'},{label:'육성 패키지',value:'목적형 상품',note:'구성 확인'},{label:'장비·혜택',value:'구성형 상품',note:'정확한 상품명 확인'}], checks:['린M: 잊혀진 유산 상품인지 확인합니다.','다이아인지 패키지인지 정확히 구분합니다.','가격·수량·처리 조건을 신청 전에 재확인합니다.'], links:[{href:'/린M충전방법',label:'린M 충전방법',text:'단계별 이용 절차'},{href:'/린M다이아',label:'린M 다이아',text:'다이아 정보 확인'},{href:'/린M가격',label:'린M 가격',text:'가격 비교 기준'}] },
  '린M가격': { kicker:'PRICE REFERENCE', referenceTitle:'가격은 같은 조건끼리 비교합니다', referenceNote:'다이아 단품과 패키지는 구성 기준이 다르므로 같은 방식으로 단순 비교하지 않습니다.', summary:'린M 가격 페이지는 다이아와 패키지를 구분하고 실제 결제 전에 최종 조건을 확인하도록 구성합니다.', facts:[{label:'다이아',value:'수량별 비교',note:'수량과 금액 확인'},{label:'패키지',value:'구성별 비교',note:'포함 상품 확인'},{label:'최종 금액',value:'신청 전 확인',note:'상담 조건 재확인'}], checks:['다이아는 수량 대비 가격을 비교합니다.','패키지는 구성과 목적을 함께 비교합니다.','실제 상담 조건은 결제 전에 확인합니다.'], links:[{href:'/린M다이아',label:'린M 다이아',text:'다이아 이용 정보'},{href:'/린M할인',label:'린M 할인',text:'할인 적용 기준'},{href:'/린M패키지',label:'린M 패키지',text:'패키지 구성 비교'}] },
  '린M패키지': { kicker:'PACKAGE SELECT', referenceTitle:'패키지는 가격보다 구성을 먼저 비교합니다', referenceNote:'상품명·구성·목적을 함께 확인하는 방식으로 안내합니다.', summary:'린M 패키지는 어떤 성장 구간과 목적을 위한 구성인지 확인하는 것이 중요합니다.', facts:[{label:'육성형',value:'성장 목적',note:'육성에 필요한 구성 확인'},{label:'장비형',value:'장비 목적',note:'포함 구성 확인'},{label:'혜택형',value:'혜택 목적',note:'적용 조건 확인'}], checks:['정확한 패키지명과 단계를 확인합니다.','포함 구성과 사용 목적을 함께 봅니다.','기간·구매 횟수 등 조건을 확인합니다.'], links:[{href:'/린M가격',label:'린M 가격',text:'가격 비교 기준'},{href:'/린M아이템',label:'린M 아이템',text:'상품 유형 확인'},{href:'/린M충전',label:'린M 충전',text:'충전 이용 정보'}] },
  '린M아이템': { kicker:'ITEM GUIDE', referenceTitle:'상품 유형을 목적별로 나눠 확인합니다', referenceNote:'다이아 가격과 겹치지 않도록 상품 종류와 선택 기준에 집중합니다.', summary:'린M 아이템 페이지는 무엇을 선택할 수 있는지 상품 유형부터 확인하려는 검색자를 위한 페이지입니다.', facts:[{label:'다이아',value:'재화형',note:'수량 기준 비교'},{label:'육성 상품',value:'성장 목적',note:'필요 성장 구간 확인'},{label:'장비 상품',value:'장비 목적',note:'구성 확인'},{label:'혜택 상품',value:'혜택 목적',note:'적용 조건 확인'}], checks:['현재 필요한 성장 목적과 맞는지 확인합니다.','구성형 상품은 포함 품목을 확인합니다.','구매 가능 여부는 최신 상담 기준으로 확인합니다.'], links:[{href:'/린M패키지',label:'린M 패키지',text:'구성형 상품 선택 기준'},{href:'/린M다이아',label:'린M 다이아',text:'핵심 재화 정보'},{href:'/린M충전방법',label:'린M 충전방법',text:'상품 결정 후 절차'}] },
  '린M충전방법': { kicker:'STEP BY STEP', referenceTitle:'상품 확인부터 완료 확인까지 4단계', referenceNote:'필요한 상품과 수량, 최종 조건을 확인한 뒤 진행하는 흐름으로 안내합니다.', summary:'린M 충전방법 페이지는 상품 설명보다 실제 이용 순서를 알고 싶은 검색자를 위한 절차형 페이지입니다.', facts:[{label:'STEP 01',value:'상품 확인',note:'상품명·수량 확인'},{label:'STEP 02',value:'가격 확인',note:'최종 금액 확인'},{label:'STEP 03',value:'상담·신청',note:'필요 정보 확인'},{label:'STEP 04',value:'완료 확인',note:'처리 결과 확인'}], checks:['게임명·상품명·수량을 정리합니다.','결제 전 최종 금액을 확인합니다.','완료 후 적용 여부를 확인합니다.'], links:[{href:'/린M충전',label:'린M 충전',text:'충전 상품 유형'},{href:'/린M가격',label:'린M 가격',text:'가격 비교'},{href:'/린M자주묻는질문',label:'린M FAQ',text:'이용 전 질문 확인'}] },
  '린M할인': { kicker:'DISCOUNT CHECK', referenceTitle:'할인은 숫자보다 적용 조건을 먼저 확인합니다', referenceNote:'확정되지 않은 할인율이나 판매가를 임의로 표시하지 않고 실제 조건을 상담 시 확인합니다.', summary:'린M 할인 페이지는 고정 할인율을 과장하기보다 적용 상품과 조건, 최종 금액 확인에 초점을 맞춥니다.', facts:[{label:'대상 상품',value:'상담 시 확인',note:'상품별 조건 확인'},{label:'할인 조건',value:'적용 여부 확인',note:'기간·수량 등 확인'},{label:'최종 금액',value:'신청 전 확인',note:'결제 전 재확인'}], checks:['할인율보다 실제 결제 금액을 비교합니다.','기간·수량 등 별도 조건을 확인합니다.','최종 상담 금액을 신청 전에 확인합니다.'], links:[{href:'/린M가격',label:'린M 가격',text:'가격 비교 기준'},{href:'/린M다이아',label:'린M 다이아',text:'다이아 정보'},{href:'/린M충전',label:'린M 충전',text:'충전 상품 정보'}] },
  '린M자주묻는질문': { kicker:'LINM FAQ', referenceTitle:'문의 전에 많이 확인하는 핵심 질문', referenceNote:'가격·충전·상품 선택처럼 반복되는 질문은 짧게 답하고, 상세 설명이 필요한 내용은 전용 페이지로 연결합니다.', summary:'린M: 잊혀진 유산의 다이아와 충전을 처음 알아보는 이용자가 자주 묻는 내용을 한곳에 정리했습니다. 답변은 과장된 보장보다 확인해야 할 기준을 중심으로 제공합니다.', facts:[{label:'어떤 게임인가요?',value:'린M: 잊혀진 유산',note:'리니지M과 구분해 안내'},{label:'무엇을 문의하나요?',value:'다이아·상품·충전',note:'상품명과 수량을 준비'},{label:'가격은 어떻게 확인하나요?',value:'최종 조건 확인',note:'상품·수량별 상담 기준'},{label:'어디로 문의하나요?',value:'전화·카카오톡',note:'빠른 상담 채널 제공'}], checks:['문의 전 정확한 게임명과 원하는 상품명을 확인합니다.','가격 문의 시 원하는 수량까지 함께 전달합니다.','결제나 진행 전 최종 상품·금액·조건을 다시 확인합니다.'], links:[{href:'/린M충전방법',label:'린M 충전방법',text:'처음 이용할 때의 단계별 흐름'},{href:'/린M가격',label:'린M 가격',text:'가격을 비교할 때 확인할 기준'},{href:'/린M다이아',label:'린M 다이아',text:'다이아의 용도와 선택 정보'}] },
  '린M가이드': { kicker:'BEGINNER GUIDE', referenceTitle:'처음 시작할 때 먼저 볼 정보', referenceNote:'판매 정보만 나열하지 않고 게임명 확인, 재화와 상품의 차이, 구매 전 체크 순서처럼 초보자가 이해하기 쉬운 정보 허브로 운영합니다.', summary:'린M 가이드는 린M: 잊혀진 유산을 처음 접하거나 다이아와 패키지의 차이가 헷갈리는 이용자를 위한 정보형 허브입니다. 구매 의도보다 이해와 탐색에 초점을 둡니다.', facts:[{label:'01',value:'게임 확인',note:'린M: 잊혀진 유산 기준'},{label:'02',value:'다이아 이해',note:'핵심 재화와 사용 목적'},{label:'03',value:'상품 구분',note:'단품·아이템·패키지 차이'},{label:'04',value:'구매 전 체크',note:'가격과 조건 재확인'}], checks:['검색 결과의 린M이 같은 게임을 의미하는지 먼저 확인합니다.','다이아와 패키지는 목적과 비교 방식이 다르다는 점을 이해합니다.','이벤트·업데이트로 상품 조건이 달라질 수 있으므로 최신 정보를 확인합니다.'], links:[{href:'/린M다이아',label:'린M 다이아',text:'핵심 재화부터 알아보기'},{href:'/린M패키지',label:'린M 패키지',text:'구성형 상품 비교하기'},{href:'/린M업데이트',label:'린M 업데이트',text:'변경된 내용 확인하기'}] },
  '린M이벤트': { kicker:'CURRENT EVENT', referenceTitle:'현재 진행 여부와 기간을 먼저 확인합니다', referenceNote:'이벤트는 시의성이 가장 중요한 정보이므로 시작일·종료일·대상·혜택을 확인할 수 있을 때만 현재 이벤트로 표시하고, 종료된 내용은 별도로 구분합니다.', summary:'린M 이벤트 페이지는 린M: 잊혀진 유산의 이벤트 정보를 최신 상태로 관리하기 위한 전용 영역입니다. 오래된 이벤트를 현재 혜택처럼 보이게 하지 않는 것을 기본 원칙으로 합니다.', facts:[{label:'진행 상태',value:'현재/종료 구분',note:'종료 이벤트와 분리'},{label:'기간',value:'날짜 기준 확인',note:'시작·종료일 확인'},{label:'대상',value:'참여 조건 확인',note:'계정·상품 조건 확인'},{label:'혜택',value:'공식 내용 기준',note:'확인된 내용만 요약'}], checks:['이벤트 종료일을 먼저 확인합니다.','참여 대상과 별도 조건이 있는지 확인합니다.','상품 구매와 연결되는 경우 실제 적용 조건을 다시 확인합니다.'], links:[{href:'/린M업데이트',label:'린M 업데이트',text:'이벤트와 함께 변경된 게임 내용 확인'},{href:'/린M패키지',label:'린M 패키지',text:'이벤트 관련 패키지 선택 기준'},{href:'/린M가이드',label:'린M 가이드',text:'게임 정보와 기본 이용 가이드'}] },
  '린M업데이트': { kicker:'UPDATE NOTE', referenceTitle:'패치 날짜와 변경 범위를 기준으로 정리합니다', referenceNote:'업데이트 페이지는 최신 패치의 날짜와 핵심 변경사항을 중심으로 관리하고, 확인되지 않은 예측이나 루머는 정보 영역에 섞지 않습니다.', summary:'린M 업데이트 페이지는 린M: 잊혀진 유산의 패치와 신규 콘텐츠, 상품 관련 변경을 빠르게 파악하려는 이용자를 위한 정보 페이지입니다. 변경 전후를 구분해 읽기 쉽게 정리합니다.', facts:[{label:'패치 날짜',value:'최신순 정리',note:'최근 변경부터 확인'},{label:'콘텐츠',value:'핵심 변경 요약',note:'신규·개선 내용 구분'},{label:'상품',value:'관련 변경 확인',note:'구성·판매 변경 여부'},{label:'영향',value:'관련 페이지 연결',note:'다이아·패키지 정보 갱신'}], checks:['게시 날짜와 실제 적용 날짜를 구분해 확인합니다.','상품 관련 변경은 기존 가격·패키지 정보에도 반영합니다.','이벤트성 변경은 업데이트와 이벤트 페이지를 서로 연결해 관리합니다.'], links:[{href:'/린M이벤트',label:'린M 이벤트',text:'현재 진행 이벤트 확인'},{href:'/린M가이드',label:'린M 가이드',text:'변경사항을 이해하기 위한 기본 정보'},{href:'/린M패키지',label:'린M 패키지',text:'상품 구성 변경 시 비교 정보 확인'}] }
};